
BINARY_PATH = "./dist/capierre_binary"
BINARY_FILE_NAME = './capierre_binary'
MAGIC_NUMBER_START = "CAPIERRE"
MAGIC_NUMBER_END = "EERIPAC"
MAGIC_NUMBER_START_LEN = len(MAGIC_NUMBER_START)
MAGIC_NUMBER_END_LEN = len(MAGIC_NUMBER_END)
