name: Build Capierre Binary Ubuntu v.20.04 & v.22.04

on:
  push:
    branches:
      - main 
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-20.04, ubuntu-22.04]
        python-version: [3.9, 3.10.x, 3.11, 3.12]
      fail-fast: false
      
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: pip
      - run: |
          pip3 install -r tool/requirements.txt

      - name: Install dependencies & Build binary
        working-directory: ./tool
        run: |
          pyinstaller \
            --collect-all z3        \
            --collect-all pyvex     \
            --collect-all angr      \
            --collect-all unicorn   \
            --collect-all cle       \
            --onefile --name capierre_binary src/__main__.py

      - name: Binary Test
        working-directory: ./tool
        run: |
          ./dist/capierre_binary --help
          ./dist/capierre_binary --version
          ./dist/capierre_binary --conceal --file ./tests/src/main.cpp --file-to-hide ./tests/src/HIDDEN_FILE
          ./dist/capierre_binary -r --file ./capierre_binary

      - name: Tests Fonctionnels
        working-directory: ./tool
        run: |
          chmod +x launch_tests.sh
          ./launch_tests.sh "fonctionnel"
