name: Build Capierre Binary MacOS v.13, v.14 et v.15

on:
  push:
    branches:
      - main 
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        compiler: [gcc-14]
        os: [macos-13, macos-14, macos-15]
        python-version: [3.9, 3.10.x, 3.11, 3.12]
      fail-fast: false

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: pip
      - run: |
          brew install pyqt5
          arch -x86_64 pip3 install -r tool/requirements.txt

      - name: Setup C/C++ Compiler
        id: setup-compiler
        uses: rlalik/setup-cpp-compiler@master
        with:
          compiler: gcc-14

      - name: Verify GCC Installation
        run: |
          ln -sf /usr/local/bin/gcc-14 /usr/local/bin/gcc
          ln -sf /usr/local/bin/g++-14 /usr/local/bin/g++
          gcc --version
          g++ --version
  
      - name: Build binary
        working-directory: ./tool
        run: |
          arch -x86_64 pyinstaller \
            --collect-all z3        \
            --collect-all pyvex     \
            --collect-all angr      \
            --collect-all unicorn   \
            --collect-all cle       \
            --onefile --name capierre_binary src/__main__.py

      - name: Binary Test
        working-directory: ./tool
        run: |
          ./dist/capierre_binary --help
          ./dist/capierre_binary --version
          ./dist/capierre_binary --conceal --file ./tests/src/main.cpp --file-to-hide ./tests/src/HIDDEN_FILE --password "password"
          ./dist/capierre_binary -r --file ./capierre_binary --password "password"

      - name: Tests Fonctionnels
        working-directory: ./tool
        run: |
          chmod +x launch_tests.sh
          ./launch_tests.sh "fonctionnel"

      - name: Build gui
        working-directory: ./gui
        run: |
          arch -x86_64 pyinstaller                                \
            --collect-all z3                                      \
            --collect-all pyvex                                   \
            --collect-all angr                                    \
            --collect-all unicorn                                 \
            --collect-all cle                                     \
            --paths=../tool/src                                   \
            --add-data "style.qss:."                              \
            --add-data "./challenges:./challenges"                \
            --add-data "./challenge_files:./challenge_files"      \
            --add-data "./expected_output:./expected_output"      \
            --onefile --name capierre_gui main.py

      - name: Upload gui artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.os }}-gui
          path: dist/capierre_gui*

      - name: Upload binary artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.os }}-cmd
          path: dist/capierre_cmd*

  release:
    name: Create Release
    needs: build
    runs-on: ${{ matrix.os }}
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          name: Release ${{ github.ref_name }}
          tag_name: ${{ github.ref }}
          files: artifacts/**/gui*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          name: Release ${{ github.ref_name }}
          tag_name: ${{ github.ref }}
          files: artifacts/**/cmd*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
