name: Build Capierre Binary Windows

on:
  push:
    branches:
      - main 
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [windows-latest]
        python-version: [3.8, 3.9, 3.10, 3.11, 3.12]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies & Build binary
        working-directory: ./tool
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pyinstaller `
            --collect-all z3        `
            --collect-all pyvex     `
            --collect-all angr      `
            --collect-all unicorn   `
            --onefile --name capierre_binary src/__main__.py

      - name: Tests Fonctionnels
        working-directory: ./tool
        run: |
          ./launch_tests.bat "fonctionnel"
