name: Build Capierre Binary Windows

on:
  push:
    branches:
      - main 
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [windows-latest]
        python-version: [3.8, 3.9, 3.10.x, 3.11, 3.12]
      fail-fast: false

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Setup C/C++ Compiler
        id: setup-compiler
        uses: rlalik/setup-cpp-compiler@master
        with:
          compiler: gcc-latest

      - name: Verify GCC Installation
        run: |
          gcc --version
          g++ --version

      - name: Install dependencies & Build binary
        working-directory: ./tool
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          python -m PyInstaller `
            --collect-all z3        `
            --collect-all pyvex     `
            --collect-all angr      `
            --collect-all unicorn   `
            --collect-all cle       `
            --onefile --name capierre_binary src/__main__.py

      - name: Binary Test
        working-directory: ./tool
        run: |
          ./dist/capierre_binary.exe --help
          ./dist/capierre_binary.exe --version
          ./dist/capierre_binary.exe --conceal --file ./tests/src/main.cpp --file-to-hide ./tests/src/HIDDEN_FILE

      - name: Tests Fonctionnels
        working-directory: ./tool
        run: |
          ./launch_tests.bat "fonctionnel"
