name: Capierre All Tests

on:
  push:
    branches:
      - main 
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies & Build binary
        working-directory: ./tool
        run: |
          pip3 install -r requirements.txt
          pyinstaller \
            --collect-all z3        \
            --collect-all pyvex     \
            --collect-all angr      \
            --collect-all unicorn   \
            --onefile --name capierre_binary src/__main__.py

      - name: Tests Fonctionnels
        working-directory: ./tool
        run: |
          chmod +x launch.sh
          ./launch.sh "fonctionnel"