name: Build Capierre Binary MacOS v.10.15, v.11.0 & v.12

on:
  push:
    branches:
      - main 
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        compiler: [gcc-14]
        os: [macos-13, macos-14, macos-15]
        python-version: [3.8, 3.9, 3.10.x, 3.11, 3.12]
      fail-fast: false

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Setup C/C++ Compiler
        id: setup-compiler
        uses: rlalik/setup-cpp-compiler@master
        with:
          compiler: gcc-14

      - name: Verify GCC Installation
        run: |
          gcc --version
          g++ --version
  
      - name: Install dependencies & Build binary
        working-directory: ./tool
        run: |
          pip3 install -r requirements.txt
          pyinstaller \
            --collect-all z3        \
            --collect-all pyvex     \
            --collect-all angr      \
            --collect-all unicorn   \
            --collect-all cle       \
            --onefile --name capierre_binary src/__main__.py

      - name: Tests Fonctionnels
        working-directory: ./tool
        run: |
          chmod +x launch_tests.sh
          ./launch_tests.sh "fonctionnel"
